database:
  echo: false
  pool_size: 20
environment: production
features:
  debug_mode: true
  experimental_features: true
  hot_reload: true
gpu:
  auto_detect: true
  device_id: 0
  enabled: true
  engines:
    geoid_processor:
      batch_threshold: 5
      enabled: true
      max_batch_size: 32
    integration_system:
      enabled: true
      max_concurrent_tasks: 8
      monitoring_interval: 1.0
    thermodynamic_engine:
      enabled: true
      ensemble_size: 1024
      precision: mixed
  fallback:
    cpu_fallback: true
    retry_attempts: 3
    timeout: 30.0
  memory_management:
    auto_clear_cache: true
    cache_enabled: true
    growth_enabled: true
    memory_fraction: 0.5
  processing:
    async_processing: true
    batch_size: 16
    optimization_level: standard
    parallel_streams: 2
logging:
  level: INFO
  structured: false
monitoring:
  detailed_metrics: true
  enabled: true
  health_check_interval: 30
  memory_tracking: true
  performance_tracking: true
  thresholds:
    cpu_critical: 95.0
    cpu_warning: 80.0
    disk_critical: 95.0
    disk_warning: 85.0
    gpu_memory_critical: 95.0
    gpu_memory_warning: 85.0
    memory_critical: 95.0
    memory_warning: 80.0
    response_time_critical: 5.0
    response_time_warning: 2.0
performance:
  gpu_memory_fraction: 0.5
  max_threads: 8
security:
  cors_enabled: true
  https_only: true
  rate_limit_enabled: true
server:
  host: 0.0.0.0
  port: 8000
  reload: false
