global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kimera SWM Application (when running)
  - job_name: 'kimera-swm'
    static_configs:
      - targets: ['host.docker.internal:8001']  # Kimera FastAPI runs on port 8001
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Kimera Monitoring System (dedicated metrics port)
  - job_name: 'kimera-monitoring'
    static_configs:
      - targets: ['host.docker.internal:9090']  # Monitoring system metrics port
    metrics_path: '/metrics'
    scrape_interval: 5s

  # PostgreSQL Database Metrics (if postgres_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Neo4j Metrics (if available)
  - job_name: 'neo4j'
    static_configs:
      - targets: ['kimera-neo4j:2004']
    scrape_interval: 30s

  # Node/System Metrics (if node_exporter is added)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 