[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = false
extend-exclude = '''
/(
    backup_.*
    | \.venv
    | \.mypy_cache
    | \.pytest_cache
    | __pycache__
)/
'''
