automation_settings:
  auto_fix_formatting: true
  auto_generate_missing: true
  generate_reports: true
  validate_on_commit: true
documentation_quality_rules:
  content_standards:
    grammar_check: true
    require_examples: true
    require_usage_section: true
    spell_check: true
    terminology_consistency: true
  markdown_standards:
    consistent_list_style: true
    heading_hierarchy: true
    max_line_length: 120
    no_bare_urls: true
    require_description: true
    require_title: true
  quality_gates:
    maximum_broken_links: 0
    maximum_spelling_errors: 5
    minimum_doc_coverage: 80
    require_code_examples: true
  structure_standards:
    api_doc_required_sections:
    - Overview
    - Classes
    - Functions
    - Examples
    readme_required_sections:
    - Description
    - Installation
    - Usage
    - Contributing
