line-length = 88
target-version = "py311"
select = ["E", "F", "W", "C90", "I", "N", "D", "S", "B", "A", "COM", "C4", "DTZ", "T10", "EM", "EXE", "ISC", "ICN", "G", "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SIM", "TID", "TCH", "ARG", "PTH", "ERA", "PD", "PGH", "PL", "TRY", "NPY", "RUF"]
ignore = ["D100", "D101", "D102", "D103", "D104", "D105"]
exclude = ["backup_*", ".venv", ".mypy_cache", ".pytest_cache", "__pycache__"]
