tcse:
  enabled: true
  mode: "balanced"  # conservative, balanced, aggressive
  
  signal_evolution:
    batch_size: 32
    evolution_rate: 0.8
    thermal_budget_threshold: 75.0
    
  thermodynamic_constraints:
    entropy_accuracy_threshold: 0.985
    energy_conservation_threshold: 0.995
    reversibility_threshold: 0.85
    
  quantum_signal:
    coherence_threshold: 0.7
    decoherence_correction: true
    superposition_max_states: 8
    
  consciousness_detection:
    consciousness_threshold: 0.7
    phi_calculation_enabled: true
    global_workspace_enabled: true
    
  performance:
    max_memory_overhead_percent: 25
    min_performance_retention_percent: 90
    real_time_monitoring: true 