REDIS_CA_CERTS: ''
REDIS_CA_PATH: ''
REDIS_CERT_REQS: required
REDIS_CLUSTER_MODE: 'false'
REDIS_CLUSTER_NODES: ''
REDIS_DB: '0'
REDIS_DECODE_RESPONSES: 'true'
REDIS_ENCODING: utf-8
REDIS_HEALTH_CHECK_INTERVAL: '30'
REDIS_HOST: localhost
REDIS_MAX_CONNECTIONS: '50'
REDIS_PASSWORD: ''
REDIS_PORT: '6379'
REDIS_RETRY_ON_TIMEOUT: 'true'
REDIS_SKIP_FULL_COVERAGE_CHECK: 'false'
REDIS_SOCKET_CONNECT_TIMEOUT: '5.0'
REDIS_SOCKET_TIMEOUT: '5.0'
REDIS_SSL: 'false'
REDIS_SSL_CERTFILE: ''
REDIS_SSL_KEYFILE: ''
REDIS_USERNAME: ''
