version: '3.8'

services:
  kimera-core:
    build:
      context: .
      dockerfile: Dockerfile.kimera
    environment:
      - KIMERA_ENV=${KIMERA_ENV:-development}
      - KIMERA_DB_PASSWORD=${KIMERA_DB_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
      - neo4j

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=kimera_${KIMERA_ENV:-dev}
      - POSTGRES_USER=kimera_user
      - POSTGRES_PASSWORD=${KIMERA_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/${KIMERA_DB_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning

volumes:
  postgres_data:
  redis_data:
  neo4j_data:
  prometheus_data:
  grafana_data: 