global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rule files for alerting
rule_files:
  - "alerts.yml"

# Scrape configurations for all production services
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kimera SWM Application
  - job_name: 'kimera-swm'
    static_configs:
      - targets: ['kimera_app_prod:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s

  # Kimera Health Endpoint
  - job_name: 'kimera-health'
    static_configs:
      - targets: ['kimera_app_prod:8002']
    metrics_path: '/health/metrics'
    scrape_interval: 10s

  # PostgreSQL Database Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['kimera_postgres_exporter:9187']
    scrape_interval: 30s

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['kimera_redis_exporter:9121']
    scrape_interval: 30s

  # Neo4j Graph Database Metrics
  - job_name: 'neo4j'
    static_configs:
      - targets: ['kimera_neo4j_prod:2004']
    scrape_interval: 30s
    scrape_timeout: 10s

  # System/Node Metrics
  - job_name: 'node'
    static_configs:
      - targets: ['kimera_node_exporter:9100']
    scrape_interval: 30s

  # Docker Container Metrics (if cAdvisor is added)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # GPU Metrics (Custom exporter for NVIDIA metrics)
  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['kimera_app_prod:8003']  # Custom GPU metrics endpoint
    metrics_path: '/gpu/metrics'
    scrape_interval: 10s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - kimera_alertmanager:9093

# Remote storage (optional for long-term storage)
# remote_write:
#   - url: "http://victoriametrics:8428/api/v1/write"