# Optimized Kimera SWM Configuration
# ==================================

system:
  mode: "optimized"
  startup_mode: "progressive"
  enable_gpu: true
  enable_monitoring: true
  enable_caching: true
  
performance:
  # Threading
  max_workers: 16
  thread_pool_size: 32
  async_io_threads: 8
  
  # Memory
  memory_limit_gb: 16
  cache_size_mb: 2048
  gc_threshold: 100000
  
  # Batch processing
  default_batch_size: 64
  max_batch_size: 256
  dynamic_batching: true
  
cognitive:
  # Engine settings
  parallel_engines: true
  engine_timeout_s: 30
  retry_failed_operations: true
  
  # Processing
  embedding_cache_size: 10000
  context_window_size: 8192
  attention_heads: 16
  
thermodynamic:
  # Efficiency
  target_efficiency: 0.85
  min_efficiency: 0.3
  optimization_interval_s: 10
  
  # Monitoring
  alert_threshold: 0.4
  auto_optimize: true
  
database:
  # Connection pooling
  pool_size: 20
  max_overflow: 10
  pool_timeout: 30
  
  # Performance
  enable_wal: true
  cache_size: 8192
  synchronous: "NORMAL"
  
api:
  # Rate limiting
  rate_limit_enabled: true
  requests_per_minute: 600
  burst_size: 100
  
  # Caching
  response_cache_ttl: 300
  enable_compression: true
  
monitoring:
  # Metrics
  collect_interval_s: 10
  retention_hours: 168
  
  # Alerts
  cpu_alert_threshold: 90
  memory_alert_threshold: 85
  gpu_alert_threshold: 95
