
name: Quality Gates

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-gates:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort ruff mypy bandit safety pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Code formatting check (Black)
      run: black --check --config config/quality/black.toml src/ tests/
    
    - name: Import sorting check (isort)  
      run: isort --check-only --profile black src/ tests/
    
    - name: Code linting (Ruff)
      run: ruff check --config config/quality/ruff.toml src/ tests/
    
    - name: Type checking (MyPy)
      run: mypy --config-file config/quality/mypy.ini src/
    
    - name: Security check (Bandit)
      run: bandit -r src/ -f json -o reports/bandit.json -c config/quality/bandit.yaml
    
    - name: Dependency vulnerability check (Safety)
      run: safety check --json --output reports/safety.json
    
    - name: Run tests with coverage
      run: pytest --cov=src --cov-report=xml --cov-report=html -c config/quality/pytest.toml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
